//
//

export default {
  login: 'bdog72',
  id: 20337443,
  node_id: 'MDQ6VXNlcjIwMzM3NDQz',
  avatar_url: 'https://avatars1.githubusercontent.com/u/20337443?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/bdog72',
  html_url: 'https://github.com/bdog72',
  followers_url: 'https://api.github.com/users/bdog72/followers',
  following_url: 'https://api.github.com/users/bdog72/following{/other_user}',
  gists_url: 'https://api.github.com/users/bdog72/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/bdog72/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/bdog72/subscriptions',
  organizations_url: 'https://api.github.com/users/bdog72/orgs',
  repos_url: 'https://api.github.com/users/bdog72/repos',
  events_url: 'https://api.github.com/users/bdog72/events{/privacy}',
  received_events_url: 'https://api.github.com/users/bdog72/received_events',
  type: 'User',
  site_admin: false,
  name: 'Brian Bycynski',
  company: null,
  blog: '',
  location: 'St. Petersburg, FL',
  email: null,
  hireable: null,
  bio: 'JR Front End Web Developer',
  twitter_username: null,
  public_repos: 412,
  public_gists: 0,
  followers: 4,
  following: 0,
  created_at: '2016-07-07T11:06:34Z',
  updated_at: '2020-10-04T04:39:57Z',
};

// export default {
//   login: 'john-smilga',
//   id: 42133389,
//   node_id: 'MDQ6VXNlcjQyMTMzMzg5',
//   avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
//   gravatar_id: '',
//   url: 'https://api.github.com/users/john-smilga',
//   html_url: 'https://github.com/john-smilga',
//   followers_url: 'https://api.github.com/users/john-smilga/followers',
//   following_url:
//     'https://api.github.com/users/john-smilga/following{/other_user}',
//   gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
//   starred_url:
//     'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
//   subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
//   organizations_url: 'https://api.github.com/users/john-smilga/orgs',
//   repos_url: 'https://api.github.com/users/john-smilga/repos',
//   events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
//   received_events_url:
//     'https://api.github.com/users/john-smilga/received_events',
//   type: 'User',
//   site_admin: false,
//   name: 'John Smilga',
//   company: 'Coding Addict',
//   blog: 'www.johnsmilga.com',
//   location: 'Los Angeles',
//   email: null,
//   hireable: null,
//   bio: 'Creator of Coding Addict',
//   twitter_username: 'john_smilga',
//   public_repos: 152,
//   public_gists: 0,
//   followers: 1495,
//   following: 0,
//   created_at: '2018-08-06T06:48:23Z',
//   updated_at: '2020-07-08T05:01:32Z',
// };
